name: 'SemVer.Guard'
description: 'Validate semantic version of npm package'

branding:
  icon: git-merge
  color: black

outputs:
  name:
    value: ${{steps.guard.outputs.name}}
  version:
    value: ${{steps.guard.outputs.version}}
  increased:
    value: ${{steps.guard.outputs.increased}}

runs:
  using: 'composite'
  steps:
    - id: guard
      run: |
        package_name=$(jq -r '.name' package.json)
        echo "Package name: $package_name"
        echo "name=${package_name}" >> $GITHUB_OUTPUT

        commit_version=$(jq -r '.version' package.json)
        echo "Commit version: $commit_version"

        latest_version=$(npm info ${package_name} version 2>/dev/null || echo "nonexistent")
        echo "Latest version: $latest_version"

        if [ "$latest_version" = "nonexistent" ]; then
          echo "Package does not exist on npm. Return new version."
          echo "increased=true" >> $GITHUB_OUTPUT
          echo "version=${commit_version}" >> $GITHUB_OUTPUT
        elif [ "$latest_version" \> "$commit_version" ] || [ "$latest_version" = "$commit_version" ]; then
          echo "Version must be greater than ${latest_version}! Stopping job."
          echo "increased=false" >> $GITHUB_OUTPUT
        else
          echo "Version updated!"
          echo "increased=true" >> $GITHUB_OUTPUT
          echo "version=${commit_version}" >> $GITHUB_OUTPUT
        fi
      shell: bash